### ISSUE TITLE
Conflict with comments package

### ISSUE THREAD

**Issue by nrueh** [krr-up/asp-macros#9]
I got an error yesterday on the `\DEL` macro because I had the comments package and the `logics.tex` file imported. Are you aware of this @tortinator ? There is also a `\DELETE` macro in the comments package which seems to do something similar as `\DEL`...
https://github.com/krr-up/latex-style-comments/blob/aa46c8f75bd8930c8d84849b263c177ae313f758/comments.sty#L62

I do not need the `DEL` logic (and variations) so I commented the corresponding lines out for now (in fact I do need neither commands for now...)

**Comment by tortinator** [comment]
Are you using the latest version...?

**Comment by nrueh** [comment]
I pulled the latest master in both submodules...

The conflict is with these two lines:
https://github.com/krr-up/asp-macros/blob/58f24268b406313737e6a16cfd7c923688e14eb3/logics.tex#L24
https://github.com/krr-up/latex-style-comments/blob/aa46c8f75bd8930c8d84849b263c177ae313f758/comments.sty#L63

And the error `Command \DEL already defined.`

**Comment by nrueh** [comment]
Ok, sorry. It seemed to be a problem of ordering. If I put the `\usepackage{comments}` after the import of `logics.tex` it works fine...

**Comment by nrueh** [comment]
Maybe we could include this information in the latex paper template? If you agree, I can open a PR
